name: Test

on:
  workflow_run:
    workflows: [ "SSZ Generate" ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -json ./...
