name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -json ./...
